_select_data:
  aspect-ratios:
  - square
  - portrait
  - portrait-tall
  - landscape

  column-sizes:
  col-6: One Half
  col-4: One Third
  co-12: Full Width
  col-3: One Quarter
  col-6_sm_12: One Half Desktop / Stacked on Mobile
  col-4_sm_12: One Third Desktop / Stacked on Mobile
  col-3_sm_12: One Quarter Desktop / Stacked on Mobile